version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-jesse
    environment:
      POSTGRES_USER: jesse_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jesse_db
    ports:
        - 5432:5432
    restart: unless-stopped
  bot:
    build: .
    container_name: bot-jesse
    restart: unless-stopped
    volumes:
      - .:/jesse-docker
    depends_on:
      - db